version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "iamsangeeth"
      POSTGRES_DB: "ECOMMERCE"
    networks:
      - mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql

  yoursstore:
    image: ecom-pro
    restart: on-failure
    environment:
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "iamsangeeth"
      DB_PORT: "5432"
      DB_NAME: "ECOMMERCE"
    depends_on:
      - postgres
    networks:
      - mydb
    ports:
      - "8000:8000"

volumes:
  pgdata:

networks:
  mydb:
    driver: bridge